<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet'
          type='text/css'>
    <style>
        body {
            padding: 0;
            margin: 0;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

        .react-comp {
            margin: 1rem;
        }

    </style>
</head>
<body>
    <div class="react-comp" rc-type="dashboard"></div>
<script src="app.js"></script>
<script src="vendors.app.js"></script>
</body>
</html>
