<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet'
          type='text/css'>
    <link href="//cdn.muicss.com/mui-0.9.42/css/mui.min.css" rel="stylesheet"
          type="text/css"/>
    <script src="//cdn.muicss.com/mui-0.9.42/js/mui.min.js"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

        h1 {
            color: #719e40;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
        }

        .intro {
            color: #aaa;
            font-size: 18px;
            margin: 50px 0 0 0;
        }

        .content {
            width: 50%;
            text-align: center;
            margin: 40px auto;
        }

        .login {
            width: 50%;
            margin: 0 auto;
        }

        .error-msg {
            border: 1px solid;
            margin: 10px 0px;
            padding: 15px 10px 15px 50px;
            background-repeat: no-repeat;
            background-position: 10px center;
            color: #D63301;
            background-color: #FFCCBA;
        }

    </style>
</head>
<body>
<div class="content">
    <h1>Teacher's Pet</h1>
    <div class="intro">A fictitious student attendance system for demonstration purposes.</div>
    <? if (isset($_SESSION['error'])) : ?>
        <div class="error-msg"><? echo $_SESSION['error'] ?></div>
    <? endif; ?>
    </div>
    <form class="mui-form login" method="post" action="login">
        <div class="mui-textfield">
            <input required name="access_code" placeholder="Enter access code to proceed" type="text"/>
        </div>
        <input type="hidden" name="<?= $nameKey ?>" value="<?= $name ?>">
        <input type="hidden" name="<?= $valueKey ?>" value="<?= $value ?>">
        <button type="submit" class="mui-btn mui-btn--raised mui-btn--primary">Submit</button>
    </form>
</div>
</body>
</html>
